### ISSUE TITLE
E2E tracing tests should support things other than Zipkin

### ISSUE THREAD

**Issue by Harwayne** [knative/observability#50]
https://github.com/knative/pkg/blob/master/test/zipkin/util.go is used in E2E tests to verify components correctly generate traces. Currently it only supports Zipkin. It should support other tracing frameworks too. At the very least it must support Jaeger. Ideally, it would support a general interface for getting traces:

```golang
func JSONTrace(traceID string, expected int, timeout time.Duration) (trace []model.SpanModel, err error)
```
Where `[]model.SpanModel` may need to change to something more generic.

---

Jaeger appears to have two APIs to retrieve traces, https://www.jaegertracing.io/docs/1.13/apis/#trace-retrieval-apis. The gRPC API is stable, the HTTP API is considered an internal API subject to change. So we _should_ depend on the gRPC API, but to begin with, we can use the HTTP API.

---

Stackdriver seems to use https://cloud.google.com/trace/docs/reference/v1/rest/v1/projects.traces/get.

**Comment by dprotaso** [comment]
I'd consider making it generic - ie. instead of writing e2e tracing tests for every destination it might be possible to use an OpenCensus receiver 

Details: https://opencensus.io/service/receivers/opencensus

Also note there's an effort to consolidate OpenCensus & OpenTracing - https://opentelemetry.io with releases due out ~ KubeCon (I'm unsure whether it'll be GA'd then)
